# Generated by Django 4.2.2 on 2023-06-16 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_amharic', models.CharField(max_length=100)),
                ('name_afaan_oromo', models.CharField(max_length=100)),
                ('job_type_amharic', models.CharField(max_length=100)),
                ('job_type_afaan_oromo', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('square', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
