# Generated by Django 4.2.2 on 2023-06-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_location_square'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='square',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
