# Generated by Django 4.2.2 on 2023-06-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_alter_location_square'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
