# Generated by Django 4.2.2 on 2023-06-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_location_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='fullName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
