# Generated by Django 4.2.2 on 2023-06-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_location_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='fullName',
            field=models.CharField(max_length=100),
        ),
    ]
